### ISSUE TITLE
versioning startegy of writer library(s)

### ISSUE THREAD

**Issue by tobiaszuercher** [scenarioo/scenarioo-cs#4]
@bruderol shall we align the version number also in the writer library to match the scenarioo version?

i think it makes sense to align the first two number parts (Major, Minor) to indicate the alignment of the "feature level" with scenarioo.

eg: 2.1.x.y -> format supports all features of scenarioo 2.1.x

i'm not sure if we really need 4 numbers for the writer library. if so, then we use

x as the patch level,
y as the build counter

2.1.1.100 -> first patch
2.1.2.107 -> second patch

the build counter is shared across all branches that's why we may have holes. i'm not a big fan of that, but it's much easier to configure this way.

we could also do just 2.1.y for simplification (3 numbers are easier to read than 4 :))

use build number as indication for patches:
2.1.100
2.1.107 -> it's a higher build number -> bugfixes

what do you think?

cc: @adiherzog

**Comment by bruderol** [comment]
@tobiaszuercher Yes, exactly. I also think we should allign this with the supported format version.

All changes to the format (supported content features) should be reflected in the first two numbers (x.y).

In the java version we use x.y.z, where only x.y is used for the feature level (x is increased for breaking changes, y for new features without breaking changes), z is only increased for patches or smaller changes that not need allignment with the format version or other components (e.g. improvement concerning performance of the library, bugfixes, etc.). 

Therefore: 
1. please allign the x.y part with the Java version
2. use everything after (.z or whatsoever) in whatever way you prefer and is supported best by your build/tools/framework (I do not care whether there are any holes in numbering).

The number for the next official reelease should be 2.1.Z

Thank you.

**Comment by adiherzog** [comment]
I agree with @bruderol. By the way: We kind of follow the ideas of "Semantic Versioning" (http://semver.org/).
