### ISSUE TITLE
Labels on Scenario is missing in version 2.1

### ISSUE THREAD

**Issue by felixmokross** [scenarioo/scenarioo-cs#5]
the property "Labels" on the Scenario class was available in scenarioo 2.0 (resp. 0.1.6 to be precise) in C# library, but is missing now.

**Comment by bruderol** [comment]
@tobiaszuercher 
this is an issue that is blocking for Release 2.1, because this Feature was available in earlier releases of scenarioo-cs

Can you please look at this?

**Comment by tobiaszuercher** [comment]
thank you @felixmokross for the feedback. i'm actually a little bit surprised that something is missing now, sorry for that!

i'm not sure if i can squeze that in tomorrow, but it will be fixed on monday.

**Comment by tobiaszuercher** [comment]
available in 2.1.27-rc on nuget.org

thank you for the feedback!

**Comment by bruderol** [comment]
:+1: thanks for the fast fix
