### ISSUE TITLE
Initialize details property on all objects to empty Details

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo-cs#6]
For convenience:
It is very annoying when you can not simply type 
<scenarioo-object-xy>.Details.addDetail("bla", "x")

The Java Writer Library supports such convenince (all details properties are per default initialized to empty details objects).

**Comment by bruderol** [comment]
@tobiaszuercher 
Is it possible to improve this? 
(this is of course no blocker for the release)

**Comment by tobiaszuercher** [comment]
yes sure. but not before saturday. i'll do that quickly @weekend

**Comment by tobiaszuercher** [comment]
available in 2.1.27-rc on nuget.org

thank youf or the feedback!
