### ISSUE TITLE
Automatically derive ScreenshotFileName

### ISSUE THREAD

**Issue by abeggchr** [scenarioo/scenarioo-cs#7]
Following the [Tutorial](http://scenarioo.github.io/tutorial.html) I wrote something like this to write the step:

        private void WriteStep()
        {
            var step = new Step
                           {
                               StepHtml = new StepHtml(WebDriver.PageSource),
                               StepDescription = new StepDescription
                                                     {
                                                         Title = WebDriver.Title,
                                                         Index = CurrentIndex
                                                     },
                               Page = new Page(WebDriver.CstPathAndQuery)
                           };
            ScenarioDocuWriter.SaveStep(UseCase.Name, Scenario.Name, step);

            var screenshot = WebDriver.GetScreenshot().AsByteArray;
            ScenarioDocuWriter.SaveScreenshot(UseCase.Name, Scenario.Name, step, screenshot);

            ScenarioDocuWriter.Flush();
            CurrentIndex++;
        }

After importing the result to Scenarioo, the screenshots were missing. Turns out that the ScreenshotFileName attribute of the StepDescription was missing. So I added the attribute:

        private void WriteStep()
        {
            var step = new Step
                           {
                               StepHtml = new StepHtml(WebDriver.PageSource),
                               StepDescription = new StepDescription
                                                     {
                                                         Title = WebDriver.Title,
                                                         Index = CurrentIndex,
                                                         ScreenshotFileName = new ScenarioDocuFiles(null).GetScreenshotFileName(CurrentIndex)
                                                     },
                               Page = new Page(WebDriver.CstPathAndQuery)
                           };
            ScenarioDocuWriter.SaveStep(UseCase.Name, Scenario.Name, step);

            var screenshot = WebDriver.GetScreenshot().AsByteArray;
            ScenarioDocuWriter.SaveScreenshot(UseCase.Name, Scenario.Name, step, screenshot);

            ScenarioDocuWriter.Flush();
            CurrentIndex++;
        }

Proposal: Derive the ScreenshotFileName property from the Step.Index property in the ScenarioDocuWriter.SaveScreenshot() method (if ScreenshotFileName is not set).

**Comment by bruderol** [comment]
Yes, that's how it is was meant to be. But the C# library is not yet 100% consistent with the reference implementation (java library). Feel free to fix it as a PR ;-)

**Comment by adiherzog** [comment]
Furthermore ScenarioDocuFiles should probably not be part of the public API, if possible we should hide it from the API user.

**Comment by tobiaszuercher** [comment]
i have a couple of days of in december where i'll fix and cleanup a couple of things in the library & also be more consinstent with the java api.
